server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: toor
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    root: INFO
    org.example: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: INFO
