version: '3'
services:
  aplicacao:
    container_name: aplicacao-demo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
  advisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    ports:
      - "8090:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
#      - /sys/fs/cgroup/cpu,cpuacct:/sys/fs/cgroup/cpuacct,cpu
    devices:
      - /dev/kmsg:/dev/kmsg
    depends_on:
      - aplicacao

