name: CICD
on:
  push:
    branches:
      - main

env:
  JAVA_VERSION: '17'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configurar Ambiente
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'adopt'
        cache: maven

    - name: Compilar projet
      run: mvn compile

  unit-test:
    name: Testes Unitários
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2
      
      - name: Configurar o Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
          cache: maven
      
      - name: Executar Testes
        run: mvn test

  integration-test:
    name: Testes Unitários
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2
      
      - name: Configurar o Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
          cache: maven
      
      - name: Executar Testes
        run: mvn test -P integration-test
  
  system-test:
    name: System Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2
      
      - name: Configurar o Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
          cache: maven

      - name: Empacotar aplicação
        run: mvn package

      - name: Iniciar o aplicativo
        run: java -jar target/demo-codigo*.jar &
      
      - name: Esperar pela inicialização do aplicativo
        uses: sergeysova/jq-action@v2
        with:
          cmd: |
            for i in {1..30}; do
              status=$(curl --request GET 'http://localhost:8080/actuator/health' | jq -r '.status')
              if [[ "$status" == "UP" ]]; then
                echo "Aplicativo iniciado com sucesso!"
                break
              fi
              sleep 1
            done

      - name: Executar Testes
        run: mvn test -Psystem-test

  report-test:
    name: Report All Test
    runs-on: ubuntu-latest
    needs: [unit-test, integration-test, system-test]
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 10

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

  
      # - name: HTML Preview
      #   id: html_preview
      #   uses: pavi2410/html-preview-action@v2
      #   with:
      #     html_file: 'target/cucumber-reports/cucumber.html'


  # sonarqube:
  #   name: Inspeção SonarQube
  #   needs: system-test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout do código-fonte
  #       uses: actions/checkout@v2
        
  #     - name: Configurar o Java
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: ${{ env.JAVA_VERSION }}

  #     - name: Analisar com o SonarQube
  #       uses: SonarSource/sonarqube-scan-action@v1
  #       with:
  #         projectBaseDir: .
  #         token: ${{ secrets.SONARQUBE_TOKEN }}